FROM python:3.10
WORKDIR /app
RUN pip3 install numpy
RUN pip3 install --upgrade setuptools
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
COPY . .
ENTRYPOINT ["powershell.exe"]
CMD [ "python", "-m" , "flask", "run", "--host=0.0.0.0"]

